### ISSUE TITLE
Add support for Basic Auth

### ISSUE THREAD

**Issue by cptechie** [brokeh/pophttp#2]
Awesome script!

Can you add support for basic auth as well?

**Comment by brokeh** [comment]
I've added this but only given it a primitive test.

Give it a try by adding something along the lines of this to your config.ini and let me know how it goes.
```
[http://example.com]
auth=basic
username=username
password=password
```

**Comment by brokeh** [comment]
Closing this issue off as resolved as it seems to work from my testing and no response from the OP.
